cors:
  allowed-origins: http://localhost:3000,http://localhost:5173

spring:
  config:
    activate:
      on-profile: local

  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:mysql://localhost:3306/prolog?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
