spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      host: redis

  datasource:
    url: jdbc:mysql://mysql:3306/prolog?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info
